name: CI

on:
  pull_request:
  push:

jobs:
  tls-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tls-feature:
          - rustls-tls
          - native-tls
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --workspace --all-targets --no-default-features --features ${{ matrix.tls-feature }}
      - run: cargo test --workspace --lib --no-default-features --features ${{ matrix.tls-feature }}
